import type { ITranslation } from "./translation";

export interface ICategory {
  id: number;
  orderBy: number;
  name: string;
  nameTranslated: ITranslation;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  description: string;
  descriptionTranslated: ITranslation;
  enabled: boolean;
  isSampleCategory: boolean;
  seoTitle: string
  seoDescription: string
  alt: {
    main: string
  }
}
